### PR TITLE
fixing childs when the parent has the "fixie" class, instead of override...

### PR DESCRIPTION
**Pull request by eskimoblood**
fixing https://github.com/rthprog/fixie/issues/16

### CODE REVIEW

**Comment by ryhan** [comment]
Nice, merging.

**Comment by wayneashleyberry** [comment]
Can't see why, but this isn't working on this template:

```
<div class="main fixie">
    <img class="banner" data-fixie="true" width="940" height="200" />
    <div class="col alpha">
        <img height="200" width="300" />
        <h2></h2>
        <p></p>
    </div>
    <div class="col">
        <img height="200" width="300" />
        <h2></h2>
        <p></p>
    </div>
    <div class="col omega">
        <img height="200" width="300" />
        <h2></h2>
        <p></p>
    </div>
    <div class="clearfix"></div>
    <h1></h1>
    <article>
        <p></p>
        <p></p>
        <p></p>
    </article>
    <a></a>
</div>
```

it does however work on a simpler dom such as

```
<article class="fixie">
  <p></p>
  <p></p>
  <p></p>
</article>
```

**Comment by wayneashleyberry** [comment]
And a slightly different problem...

with this template:

```
<article>
  <p></p>
  <p></p>
  <p></p>
</article>
```

`fixie('article')` works as expected, the `<p>` elements are filled with content

but running `fixie('article, p')` removes the `<p>` tags :(

**Comment by ryhan** [comment]
Should be fixed now.

**Pull request merged**
